

# Directory where the outputs will be put
DIR: 'run'


# Chromosomes included
CHROM : ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22']
# Prefix of a chromosome. Usually set to 'chr' (GRCh38) or '' (hg19)
CHR_PREFIX : 'chr'

# Bowtie
BOWTIE_GENOME_INDEX : '/work-zfs/abattle4/heyuan/database/bowtie2/grch38/grch38_1kgmaj'

# STAR
STAR : '/work-zfs/abattle4/heyuan/tools/STAR-2.7.1a/bin/Linux_x86_64_static/STAR'

STAR_GENOME_INDEX : '/work-zfs/abattle4/heyuan/database/STAR/genome_index'
VCFFN : '/work-zfs/abattle4/heyuan/Variant_calling/datasets/GBR/vcf_Fn/ALL.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.GBRsampleRemoved.maf005.recode.vcf'
GENOME_STAR : '/work-zfs/abattle4/heyuan/database/STAR/Homo_sapiens.GRCh38.dna.primary_assembly.fa'
GTF : '/work-zfs/abattle4/heyuan/database/STAR/gencode_chromosomenames.v30.annotation.gtf'

# database
GENOME : '/work-zfs/abattle4/heyuan/database/GRCh38_reference/GRCh38.primary_assembly.genome.fa'

# tools
PICARD : 'picard'
GATK : '/work-zfs/abattle4/heyuan/tools/gatk-4.1.8.1/gatk'
SAMTOOLS : 'samtools'
BCFTOOLS : 'bcftools'
VCFTOOLS : 'vcftools'
THREADS : 24

# data dir
FQ_DIR : '/work-zfs/abattle4/heyuan/Variant_calling/datasets/GBR/ATAC_seq/ftp.sra.ebi.ac.uk/vol1/ERZ683'
BOWTIE_DIR : '/work-zfs/abattle4/heyuan/Variant_calling/datasets/GBR/ATAC_seq/alignment_bowtie'
STAR_DIR : '/work-zfs/abattle4/heyuan/Variant_calling/datasets/GBR/ATAC_seq/alignment_STAR'

# filter
minDP_arr : ['3', '4', '5', '6', '7', '8', '9', '10']

# output
DIR : 'output/'
