

# Directory where the outputs will be put
DIR: 'run'


# Chromosomes included
CHROM : ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22']
# Prefix of a chromosome. Usually set to 'chr' (GRCh38) or '' (hg19)
CHR_PREFIX : 'chr'

# Bowtie
BOWTIE_GENOME_INDEX : '/work-zfs/abattle4/heyuan/database/bowtie2/grch38/grch38_1kgmaj'

# Reference genome; usually a standard GRC genome
GENOME : '/work-zfs/abattle4/heyuan/database/GRCh38_reference/GRCh38.primary_assembly.genome.fa'

PICARD : 'picard'
GATK : '/work-zfs/abattle4/heyuan/tools/gatk-4.1.8.1/gatk'
SAMTOOLS : 'samtools'
BCFTOOLS : 'bcftools'
VCFTOOLS : 'vcftools'
THREADS : 24

# Experiment-specific parameters
DBSNP_COMMON : '/net/langmead-bigmem-ib.bluecrab.cluster/storage2/naechyun/bias_inspector/variant_analysis/dbsnp/common_all_20180418_renamed.vcf.gz'

# data dir
FQ_DIR : '/work-zfs/abattle4/heyuan/Variant_calling/benchmarking/datasets/GBR/ATAC_seq/ftp.sra.ebi.ac.uk/vol1/ERZ683'
BOWTIE_DIR : '/work-zfs/abattle4/heyuan/Variant_calling/benchmarking/datasets/GBR/ATAC_seq/alignment_bowtie'

# filter
minDP_arr : ['3', '4', '5', '6', '7', '8', '9', '10']

# output
DIR : 'output/'
