

# Directory where the outputs will be put
DIR: 'run'


# Chromosomes included
CHROM : ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22']
# Prefix of a chromosome. Usually set to 'chr' (GRCh38) or '' (hg19)
CHR_PREFIX : 'chr'

# tools
PICARD : 'picard'
BCFTOOLS : 'bcftools'
VCFTOOLS : 'vcftools'

THREADS : 4

# data dir
DATA_DIR : '/work-zfs/abattle4/heyuan/Variant_calling/datasets/GEO/PRJNA484801/ATAC_seq/alignment_bowtie'
TMP_DIR : '/dev/shm'

