

# Directory where the outputs will be put
DIR: 'run'


# Chromosomes included
CHROM : ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22']
CHROM : ['22']
# Prefix of a chromosome. Usually set to 'chr' (GRCh38) or '' (hg19)
CHR_PREFIX : 'chr'

# Bowtie
BOWTIE_GENOME_INDEX : '/work-zfs/abattle4/heyuan/database/bowtie2/grch38/GRCh38_noalt_as/GRCh38_noalt_as'


# tools
PICARD : 'picard'
GATK : '/work-zfs/abattle4/heyuan/tools/gatk-4.1.8.1/gatk'
SAMTOOLS : 'samtools'
BCFTOOLS : 'bcftools'
VCFTOOLS : 'vcftools'
MACS2 : '~/miniconda3/bin/macs2'
CRAMTOOLS : '~/miniconda3/bin/cramtools'
BEDTOOLS : 'bedtools'
THREADS : 24

# data dir
FQ_DIR : '/scratch/users/yhe23@jhu.edu/fastq/'
BOWTIE_DIR : '/work-zfs/abattle4/heyuan/Variant_calling/datasets/ENA/ATAC_seq/alignment_bowtie'
DATA_DIR : '/work-zfs/abattle4/heyuan/Variant_calling/datasets/ENA/ATAC_seq/alignment_bowtie'
TMP_DIR : '/dev/shm'

GENCOVE_DIR : '/work-zfs/abattle4/heyuan/Variant_calling/datasets/ENA/Gencove'

# output
DIR : 'output/'
